print("Hello World!")
print ("Hello Gunther!")
print("Hello Lukas!")
print("Hello Anna!")
print("How are you all doing?")
print("I am sending you a virtual smile :)")
print("Hello Hanna and the others!")
print("I'm fine thanks and U?")
print("LG Anna :)")
