print("Hello World!")
print ("Hello Gunther!")
print("Hello Lukas!")
print("Hello Anna!")
print("How are you all doing?")
print("I am sending you a virtual smile :)")
print("Hello Hanna and the others!")
print("I'm fine thanks and U?")
print("LG Anna :)")
print("Last minute! Joined the gang, but caused a conflict and solved it :)")
print("Hello everyone. Last week I played around with the README file, hope that's ok :)")
print("One last sentence")
print("try another merge conflict!")
print("the last and least commit without merge conflict")